### ISSUE TITLE
Keyboard navigation support

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-time-picker#12]
child of #1

Keyboard input

No strict requirements how. This is a good candidate for iteration during development.

**Comment by manolo** [comment]
What is supposed to be added here? 

Right now, because we rely on vaadin-combo-box, keyboard navigation works out of the box, focusing, blurring, arrows and enter keys work as expected when selecting an item.  User can also write a value in the text-field, and when the value is in the combo it is selected.

The only missing part might be whether we want to allow filtering items while the user types

**Comment by YuriyVaadin** [comment]
Functionality was discussed with @jouni .
Final decision was not to show dropdown when step is less than 15 mins

**Comment by manolo** [comment]
Right now, it will be quite difficult to reach e.g. 23:30 with keyboard when precision is 60 or 1 second. 

Probably we need to focus by sections as native does, and increase each section.
I'm thinking that we might reuse native accessibility by configuring native input as `type=time`
